exports.getevents = function() {

  return ([
    { series: "IMSA", year: "2017", event: "DAYTONA"  },
    { series: "IMSA", year: "2017", event: "SEBRING"  },
    { series: "IMSA", year: "2017", event: "LONG BEACH"  },
    { series: "IMSA", year: "2017", event: "COTA"  },
    { series: "IMSA", year: "2017", event: "DETROIT"  },
    { series: "IMSA", year: "2017", event: "WATKINS GLEN"  },
    { series: "IMSA", year: "2017", event: "CTMP"  },
    { series: "IMSA", year: "2017", event: "LIME ROCK"  },
    { series: "IMSA", year: "2017", event: "ROAD AMERICA"  },
    { series: "IMSA", year: "2017", event: "VIRGINIA"  },
    { series: "IMSA", year: "2017", event: "LAGUNA_SECA"  },
    { series: "WEC",  year: "2015", event: "SILVERSTONE"  },
    { series: "WEC",  year: "2015", event: "SPA"  },
    { series: "WEC",  year: "2015", event: "LE_MANS"  },
    { series: "WEC",  year: "2015", event: "NURBURGRING"  },
    { series: "WEC",  year: "2015", event: "MEXICO"  },
    { series: "WEC",  year: "2015", event: "AUSTIN"  },
    { series: "WEC",  year: "2015", event: "FUJI"  },
    { series: "WEC",  year: "2015", event: "SHANGHAI"  },
    { series: "WEC",  year: "2015", event: "BAHRAIN"  },
    { series: "WEC",  year: "2016", event: "SILVERSTONE"  },
    { series: "WEC",  year: "2016", event: "SPA"  },
    { series: "WEC",  year: "2016", event: "LE_MANS"  },
    { series: "WEC",  year: "2016", event: "NURBURGRING"  },
    { series: "WEC",  year: "2016", event: "MEXICO"  },
    { series: "WEC",  year: "2016", event: "AUSTIN"  },
    { series: "WEC",  year: "2016", event: "FUJI"  },
    { series: "WEC",  year: "2016", event: "SHANGHAI"  },
    { series: "WEC",  year: "2016", event: "BAHRAIN"  },
    { series: "WEC",  year: "2017", event: "SILVERSTONE"  },
    { series: "WEC",  year: "2017", event: "SPA"  },
    { series: "WEC",  year: "2017", event: "LE_MANS"  },
    { series: "WEC",  year: "2017", event: "NURBURGRING"  },
    { series: "WEC",  year: "2017", event: "MEXICO"  },
    { series: "WEC",  year: "2017", event: "AUSTIN"  },
  ]);

}
